title: "Senior Automation Test"
email: duykhanhrc@gmail.com
timezone: UTC
url: "https://seniorautomationtest.com"
baseurl: ""
# destination: ./docs
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Khanh
paginate: 30
#disqus: 'seniorautomationtest'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  khanh:
    name: Khanh
    display_name: Khanh Pham
    avatar: 'assets/images/avatar.jpeg'
    email: duykhanhrc@gmail.com
    web: https://seniorautomationtest.com/about/
    # twitter: https://twitter.com/wowthemesnet
    facebook: https://www.facebook.com/seniorautomationtest
    description: "Người hướng dẫn automation test."
  # john:
  #   name: John
  #   display_name: John
  #   avatar: 'assets/images/john.png'
  #   email: duykhanhrc@gmail.com
  #   web: https://www.wowthemes.net/category/jekyll-themes/
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  # instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/seniorautomationtest
  # twitter: https://twitter.com/bstartercom
  tiktok: https://www.tiktok.com/@newautomationtest

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

collections:
  services:
    output: true
