title: "Experienced Automation Testers"
email: duykhanhrc@gmail.com
timezone: UTC
url: "https://seniorautomationtest.com"
baseurl: ""
# destination: ./docs
permalink: "/:title/"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
author: Khanh
paginate: 30
#disqus: 'seniorautomationtest'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  khanh:
    name: Khanh
    display_name: Khanh Pham
    avatar: 'assets/images/avatar.jpeg'
    email: duykhanhrc@gmail.com
    web: https://seniorautomationtest.com/about/
    # twitter: https://twitter.com/wowthemesnet
    facebook: https://www.facebook.com/seniorautomationtest
    description: "Người hướng dẫn automation test."
  son:
    name: Lê Tiến Sơn
    display_name: Lê Tiến Sơn
    avatar: 'assets/images/letienson.png'
    email: letienson.30042004@gmail.com
    web: https://letienson987.github.io/contactme/
    # twitter: https://twitter.com/wowthemesnet
    description: "Người viết Blog"
    facebook: https://www.facebook.com/letienson987.EAT/

# Social
social:
  facebook: https://www.facebook.com/seniorautomationtest
  youtube: https://www.youtube.com/watch?v=NnCqivua4Yk
  tiktok: https://www.tiktok.com/@seniortester

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

collections:
  services:
    output: true
  donators:
    output: true
